--- #YAML:1.0
name:               MongooseX-JSMethod
version:            0.01
abstract:           Set a method to run MongoDB-server side.
author:
    - Fernando Correa de Oliveira <fernandocorrea@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Mongoose:    0.11
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
